-- SQLite schema for FileDatabase (FILE_INFOS/TAG_INFOS/TAG_MAPS)

CREATE TABLE IF NOT EXISTS "FILE_INFOS" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "CREATED_AT" TEXT,
    "UPDATED_AT" TEXT,
    "FOLDER_PATH" TEXT,
    "FILE_NAME" TEXT,
    "SHA_256" TEXT
);

CREATE TABLE IF NOT EXISTS "TAG_INFOS" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "CREATED_AT" TEXT,
    "UPDATED_AT" TEXT,
    "NAME" TEXT
);

CREATE TABLE IF NOT EXISTS "TAG_MAPS" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "CREATED_AT" TEXT,
    "UPDATED_AT" TEXT,
    "FILE_INFO_ID" INTEGER,
    "TAG_ID" INTEGER
);

