-- Task management schema for NyanTaskNotes
-- 目的:
--  - 単発タスクと繰り返しタスクの両方を管理
--  - 繰り返し定義は別テーブルに分離し、各発生回は OCCURRENCES に保存
--  - 例外（スキップ/振替）を個別に管理
--
-- 日付/日時はISO8601文字列（例: YYYY-MM-DD / YYYY-MM-DDTHH:MM:SS）を格納
-- 曜日表現は 0=日,1=月,2=火,3=水,4=木,5=金,6=土 を前提

PRAGMA foreign_keys = ON;
PRAGMA user_version = 3;

CREATE TABLE IF NOT EXISTS "TASKS" (
  "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
  "TITLE" TEXT NOT NULL,
  "DESCRIPTION" TEXT,
  -- 単発タスク向け期日（日時）
  "DUE_AT" TEXT,
  -- 繰り返し基準日/開始日（UIの「開始」）
  "START_DATE" TEXT,
  -- 開始時刻（任意）
  "START_TIME" TEXT,
  "IS_RECURRING" INTEGER NOT NULL DEFAULT 0,
  -- 完了時にコメント入力を促す（0/1）
  "REQUIRE_COMPLETE_COMMENT" INTEGER NOT NULL DEFAULT 0,
  "CREATED_AT" TEXT,
  "UPDATED_AT" TEXT
);

-- 繰り返し定義
CREATE TABLE IF NOT EXISTS "RECURRENCE_RULES" (
  "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
  "TASK_ID" INTEGER UNIQUE NOT NULL REFERENCES "TASKS"("ID") ON DELETE CASCADE,
  -- 繰り返し頻度: 日/週/月/年
  "FREQ" TEXT NOT NULL CHECK("FREQ" IN ('daily','weekly','monthly','yearly')),
  -- 間隔（UIの「1 日ごと」の数字）
  "INTERVAL" INTEGER NOT NULL DEFAULT 1 CHECK("INTERVAL" > 0),
  -- 終了条件: なし/日付/回数
  "END_KIND" TEXT NOT NULL DEFAULT 'none' CHECK("END_KIND" IN ('none','until','count')),
  "UNTIL_DATE" TEXT,
  "COUNT" INTEGER,
  -- 完了時に次期日を手動指定するモード
  "MANUAL_NEXT_DUE" INTEGER NOT NULL DEFAULT 0,
  -- 日次の生成ウィンドウ（日数）。daily のみで使用。既定14日。
  "HORIZON_DAYS" INTEGER DEFAULT 14,
  -- 週次用: 曜日ビットマスク（bit0=日〜bit6=土）
  "WEEKLY_DOWS" INTEGER DEFAULT 0,
  -- 月次（日付指定）: 1..31
  "MONTHLY_DAY" INTEGER,
  -- 月次（第N曜日指定）: N=1..5 / -1=最終, 曜日=0..6
  "MONTHLY_NTH" INTEGER,
  "MONTHLY_NTH_DOW" INTEGER,
  -- 年次: 対象の月(1..12)。日付/第N曜日指定は上記を併用
  "YEARLY_MONTH" INTEGER,
  "CREATED_AT" TEXT,
  "UPDATED_AT" TEXT
);

CREATE INDEX IF NOT EXISTS "IDX_RULES_TASK" ON "RECURRENCE_RULES" ("TASK_ID");

-- 各発生インスタンス（各回）
CREATE TABLE IF NOT EXISTS "TASK_OCCURRENCES" (
  "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
  "TASK_ID" INTEGER NOT NULL REFERENCES "TASKS"("ID") ON DELETE CASCADE,
  "SCHEDULED_DATE" TEXT NOT NULL,
  "SCHEDULED_TIME" TEXT,
  -- ユーザーが延期した場合の上書き日付（UI表示専用）
  "DEFERRED_DATE" TEXT,
  "STATUS" TEXT CHECK("STATUS" IN ('pending','done','skipped','cancelled')) DEFAULT 'pending',
  "COMPLETED_AT" TEXT,
  "CREATED_AT" TEXT,
  "UPDATED_AT" TEXT
);

CREATE INDEX IF NOT EXISTS "IDX_TASK_OCCURRENCES_TASK_DATE" ON "TASK_OCCURRENCES" ("TASK_ID", "SCHEDULED_DATE");
CREATE INDEX IF NOT EXISTS "IDX_TASK_OCCURRENCES_STATUS_DATE" ON "TASK_OCCURRENCES" ("STATUS", "SCHEDULED_DATE");

-- 例外（スキップ/振替）
CREATE TABLE IF NOT EXISTS "RECURRENCE_EXCEPTIONS" (
  "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
  "TASK_ID" INTEGER NOT NULL REFERENCES "TASKS"("ID") ON DELETE CASCADE,
  "EXCEPTION_DATE" TEXT NOT NULL,
  "ACTION" TEXT NOT NULL CHECK("ACTION" IN ('skip','reschedule')),
  "NEW_DATE" TEXT,
  "NEW_TIME" TEXT,
  "CREATED_AT" TEXT,
  "UPDATED_AT" TEXT
);

CREATE INDEX IF NOT EXISTS "IDX_REC_EX_TASK_DATE" ON "RECURRENCE_EXCEPTIONS" ("TASK_ID", "EXCEPTION_DATE");

-- タグ（タスク用）
CREATE TABLE IF NOT EXISTS "TAG_INFOS" (
  "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
  "NAME" TEXT NOT NULL UNIQUE,
  "CREATED_AT" TEXT,
  "UPDATED_AT" TEXT
);

CREATE TABLE IF NOT EXISTS "TASK_TAGS" (
  "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
  "TASK_ID" INTEGER NOT NULL REFERENCES "TASKS"("ID") ON DELETE CASCADE,
  "TAG_ID" INTEGER NOT NULL REFERENCES "TAG_INFOS"("ID") ON DELETE CASCADE,
  "CREATED_AT" TEXT,
  "UPDATED_AT" TEXT,
UNIQUE("TASK_ID", "TAG_ID")
);

-- イベントログ（タスク/オカレンスの操作履歴）
CREATE TABLE IF NOT EXISTS "TASK_EVENTS" (
  "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
  "CREATED_AT" TEXT NOT NULL,
  "KIND" TEXT NOT NULL,
  "SOURCE" TEXT NOT NULL CHECK("SOURCE" IN ('user','system')),
  "TASK_ID" INTEGER,
  "OCCURRENCE_ID" INTEGER,
  "DETAILS" TEXT,
  FOREIGN KEY ("TASK_ID") REFERENCES "TASKS"("ID") ON DELETE SET NULL,
  FOREIGN KEY ("OCCURRENCE_ID") REFERENCES "TASK_OCCURRENCES"("ID") ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS "IDX_TASK_EVENTS_TASK_CREATED" ON "TASK_EVENTS" ("TASK_ID", "CREATED_AT");
CREATE INDEX IF NOT EXISTS "IDX_TASK_EVENTS_OCC" ON "TASK_EVENTS" ("OCCURRENCE_ID");
CREATE INDEX IF NOT EXISTS "IDX_TASK_EVENTS_KIND_CREATED" ON "TASK_EVENTS" ("KIND", "CREATED_AT");

-- タスクとファイルの関連付け
CREATE TABLE IF NOT EXISTS "TASK_FILE_LINKS" (
  "TASK_ID" INTEGER NOT NULL REFERENCES "TASKS"("ID") ON DELETE CASCADE,
  "FILE_SHA256" TEXT NOT NULL,
  "CREATED_AT" TEXT,
  "UPDATED_AT" TEXT,
  PRIMARY KEY ("TASK_ID", "FILE_SHA256")
);

CREATE INDEX IF NOT EXISTS "IDX_TASK_FILE_LINKS_SHA" ON "TASK_FILE_LINKS" ("FILE_SHA256");
