-- Task management schema for NyanTaskNotes
-- 目的:
--  - 単発タスクと繰り返しタスクの両方を管理
--  - 繰り返し定義は別テーブルに分離し、各発生回は OCCURRENCES に保存
--  - 例外（スキップ/振替）を個別に管理
--
-- 日付/日時はISO8601文字列（例: YYYY-MM-DD / YYYY-MM-DDTHH:MM:SS）を格納
-- 曜日表現は 0=日,1=月,2=火,3=水,4=木,5=金,6=土 を前提

PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS "TASKS" (
  "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
  "TITLE" TEXT NOT NULL,
  "DESCRIPTION" TEXT,
  "STATUS" TEXT CHECK("STATUS" IN ('todo','doing','done','archived')) DEFAULT 'todo',
  "PRIORITY" INTEGER,
  -- 単発タスク向け期日（日時）
  "DUE_AT" TEXT,
  -- 繰り返し基準日/開始日（UIの「開始」）
  "START_DATE" TEXT,
  -- 開始時刻（任意）
  "START_TIME" TEXT,
  "IS_RECURRING" INTEGER NOT NULL DEFAULT 0,
  "CREATED_AT" TEXT,
  "UPDATED_AT" TEXT
);

CREATE INDEX IF NOT EXISTS "IDX_TASKS_STATUS" ON "TASKS" ("STATUS");

-- 繰り返し定義
CREATE TABLE IF NOT EXISTS "RECURRENCE_RULES" (
  "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
  "TASK_ID" INTEGER UNIQUE NOT NULL REFERENCES "TASKS"("ID") ON DELETE CASCADE,
  -- 繰り返し頻度: 日/週/月/年
  "FREQ" TEXT NOT NULL CHECK("FREQ" IN ('daily','weekly','monthly','yearly')),
  -- 間隔（UIの「1 日ごと」の数字）
  "INTERVAL" INTEGER NOT NULL DEFAULT 1 CHECK("INTERVAL" > 0),
  -- 終了条件: なし/日付/回数
  "END_KIND" TEXT NOT NULL DEFAULT 'none' CHECK("END_KIND" IN ('none','until','count')),
  "UNTIL_DATE" TEXT,
  "COUNT" INTEGER,
  -- 週次用: 曜日ビットマスク（bit0=日〜bit6=土）
  "WEEKLY_DOWS" INTEGER DEFAULT 0,
  -- 月次（日付指定）: 1..31
  "MONTHLY_DAY" INTEGER,
  -- 月次（第N曜日指定）: N=1..5 / -1=最終, 曜日=0..6
  "MONTHLY_NTH" INTEGER,
  "MONTHLY_NTH_DOW" INTEGER,
  -- 年次: 対象の月(1..12)。日付/第N曜日指定は上記を併用
  "YEARLY_MONTH" INTEGER,
  "CREATED_AT" TEXT,
  "UPDATED_AT" TEXT
);

CREATE INDEX IF NOT EXISTS "IDX_RULES_TASK" ON "RECURRENCE_RULES" ("TASK_ID");

-- 各発生インスタンス（各回）
CREATE TABLE IF NOT EXISTS "TASK_OCCURRENCES" (
  "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
  "TASK_ID" INTEGER NOT NULL REFERENCES "TASKS"("ID") ON DELETE CASCADE,
  "SCHEDULED_DATE" TEXT NOT NULL,
  "SCHEDULED_TIME" TEXT,
  "STATUS" TEXT CHECK("STATUS" IN ('pending','done','skipped','cancelled')) DEFAULT 'pending',
  "COMPLETED_AT" TEXT,
  "CREATED_AT" TEXT,
  "UPDATED_AT" TEXT
);

CREATE INDEX IF NOT EXISTS "IDX_TASK_OCCURRENCES_TASK_DATE" ON "TASK_OCCURRENCES" ("TASK_ID", "SCHEDULED_DATE");
CREATE INDEX IF NOT EXISTS "IDX_TASK_OCCURRENCES_STATUS_DATE" ON "TASK_OCCURRENCES" ("STATUS", "SCHEDULED_DATE");

-- 例外（スキップ/振替）
CREATE TABLE IF NOT EXISTS "RECURRENCE_EXCEPTIONS" (
  "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
  "TASK_ID" INTEGER NOT NULL REFERENCES "TASKS"("ID") ON DELETE CASCADE,
  "EXCEPTION_DATE" TEXT NOT NULL,
  "ACTION" TEXT NOT NULL CHECK("ACTION" IN ('skip','reschedule')),
  "NEW_DATE" TEXT,
  "NEW_TIME" TEXT,
  "CREATED_AT" TEXT,
  "UPDATED_AT" TEXT
);

CREATE INDEX IF NOT EXISTS "IDX_REC_EX_TASK_DATE" ON "RECURRENCE_EXCEPTIONS" ("TASK_ID", "EXCEPTION_DATE");

